### ISSUE TITLE
[BUG] PHP 8.2 Deprecated Functionality: Function utf8_encode()

### ISSUE THREAD

**Issue by AxxaGroup** [ParadoxLabs-Inc/cybersource#1]
API Test Results | Deprecated Functionality: Function utf8_encode() is deprecated in public_html/vendor/paradoxlabs/cybersource/Model/Service/Rest.php on line 184 See the User Manual for instructions and additional information.

Can't activate REST API because of depreciated utf8_encode

<pre><code>
CyberSource version: 1.3.2
Magento version: 2.4.6
PHP version: 8.2 

</code></pre>

**Comment by rhoerr** [comment]
Thanks for the report! We'll investigate.

**Comment by rhoerr** [comment]
Hi @steveshepherd, this should be fixed now. You can apply the patch from https://github.com/ParadoxLabs-Inc/cybersource/commit/f9d5f1f32999adec8b1a9d19d3f805082236d827.patch , or wait for the next release.

Thanks for reporting the issue
